# Generated by Django 6.0.3 on 2026-04-04 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('analyst', 'Analyst'), ('viewer', 'Viewer')], default='viewer', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='recordsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='expense')),
                ('category', models.CharField(max_length=15, verbose_name='category')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(max_length=50, verbose_name='note')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinanceManagementApp.user')),
            ],
        ),
    ]
